### ISSUE TITLE
Le SQL contient des COPY

### ISSUE THREAD

**Issue by nadineprofesseur** [cegepmatane/projet-integrite-2018-Mezeeh#1]
Corriger le fichier SQL en utilisant cette procédure 
https://docs.google.com/presentation/d/1wgC7BLUYG03NhlxPf1bETCrUEcHLA7-TICV54YkaRow/edit#slide=id.g289801d67e_0_34

**Comment by Mezeeh** [comment]
Corriger sur le dernier commit https://github.com/cegepmatane/projet-integrite-2018-Mezeeh/commit/7c910f6046644a508af578f38c759f7a0e844df1

**Comment by nadineprofesseur** [comment]
Le fichier est vide je crois
https://github.com/cegepmatane/projet-integrite-2018-Mezeeh/blob/master/Filmotheque/data/filmotheque.sql

**Comment by Mezeeh** [comment]
Bon finalement tout devrais être correct, apres un fichier qui s'est vidé bizarrement https://github.com/cegepmatane/projet-integrite-2018-Mezeeh/commit/55ecebe518cc746635851d6f17b4d99dd6ddc511
